require_relative 'intcode'

raw_input = $stdin.read

100.times do |noun|
  100.times do |verb|
    intcode = raw_input.split(/,/).map(&:to_i)

    intcode[1] = noun
    intcode[2] = verb

    begin
      run_intcode(intcode)
    rescue UnknownOpcode
      next
    end

    if intcode[0] == 19690720
      puts "Output 19690720 generated by:", "noun #{noun}", "verb #{verb}"
      puts "Answer is #{100 * noun + verb}"
      exit
    end
  end
end
